---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-controller-role
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - secrets
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - projects      
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - namespaces          
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - serviceaccounts
  - verbs:
      - '*'
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - '*'
    apiGroups:
      - 'argoproj.io'
    resources:
      - applications      
  - verbs:
      - '*'
    apiGroups:
      - 'argoproj.io'
    resources:
      - applicationset         